var data = {
    header_name: 'Mahmudul Hasan',
    about_my_self: 'I\'m a Mahmudul Hasan, Since Now, I have 4+ years plus of extensive hands on experience of website development and Web Application Development.<br> \n' +
        'I am Strong Developer and leader. I have a high level of personal morals and integrity. I am Goal oriented, self-motivated and committed to the successful outcome of the project. I am willing to work hard and have a great desire to learn.<br>\n' +
        'I am passionate about building excellent software that improves the lives of those around me<br>.\n' +
        'Currently working as a Software Engineer at TMSS-ICT.',
    contact_details : 'Feel free to get in touch with me. I am always open to discussing new projects, creative ideas or opportunities to be part of your visions.',
    banner_button_text: 'more about me',
    about_banner_resume_title: 'resume',
    about_personal_info_title: 'personal infos',
    first_name: 'Mahmudul',
    last_name: 'Hasan',
    email: 'hasanmahmudul356@gmail.com',
    phone: '01788208626',
    age: '26 Years',
    nationality: 'Bangladeshi',
    phone: '01788208626',
    freelance: 'Available',
    address: 'Dhaka, Bangladesh',
    skype: 'mahmudul.hasan7785',
    language: 'Bengali, English',
    facebook: 'https://www.facebook.com/mahmudul.bashir/',
    youtube: 'https://www.youtube.com/channel/UC15SdGXA3UGgXYcdixqmSiA',
    twitter: 'https://twitter.com/hasanmahmudul31',
    linkedin: 'https://www.linkedin.com/in/mahmudul-hasan-b41724105/',
    experience_counter: [
        {count: 4, first_text: 'years of', last_text: 'experience',},
        {count: 20, first_text: 'completed', last_text: 'projects',},
        {count: 5, first_text: 'Happy', last_text: 'customers',},
        {count: 10, first_text: 'technology', last_text: 'uses',},
    ],
    skills: [
        {name: 'PHP', percent: 80,},
        {name: 'Laravel', percent: 90,},
        {name: 'Python', percent: 50,},
        {name: 'Django', percent: 75,},
        {name: 'Javascript', percent: 80,},
        {name: 'Vue.Js', percent: 90,},
        {name: 'Firebase', percent: 50,},
        {name: 'Css', percent: 90,},
        {name: 'Bootstrap', percent: 80,},
        {name: 'Html', percent: 90,},
        {name: 'Version Control (git)', percent: 85,},
        {name: 'Docker', percent: 50,},
    ],
    experiences: [
        {
            start_date: 'March-2019',
            end_date: 'Present',
            designation: 'Software engineer',
            company: 'TMSS-ICT',
            technology: 'PHP, Laravel, Javascript, Vue.js, Git',
            projects: 'Microfinance, Education, News, Water supply, Website'
        },
        {
            start_date: 'February-2020',
            end_date: 'October-2020 (Remote)',
            designation: 'Programmer',
            company: 'Iddrak (Saudi Arabia)',
            technology: 'PHP, Laravel, Vue.js',
            projects: 'Training management, Vendor management, Website'
        },
        {
            start_date: 'July-2018 ',
            end_date: 'February-2019  (Remote)',
            designation: 'Web Design & Developer',
            company: '3D-Vision (Saudi Arabia)',
            technology: 'HTML, CSS, Javascript, PHP, Laravel, Javascript, Vue.js, Git',
            projects: 'Website, HRM & Inventory, School Management'
        },
        {
            start_date: 'September-2017',
            end_date: 'April-2018',
            designation: 'Programmer',
            company: 'Redsoft Limited',
            technology: 'HTML, CSS, Javascript, PHP, Laravel, Jquery',
            projects: 'Bill Management, News, Website, Training management, HRM, Printing press Management, Bulk SMS, POS'
        },
        {
            start_date: 'December-2016',
            end_date: 'August-2017',
            designation: 'Web Developer',
            company: 'Pacific Group',
            technology: 'PHP, CodeIgniter, Laravel, Wordpress',
            projects: 'News, HRM, POS'
        }
    ],
    educations: [
        {
            name: 'BSC in Computer Science and Engineering (CSE)',
            year: '2015',
            section: 'CSE',
            institute: 'Green University of Bangladesh',
            result: 'Appeared',
        },
        {
            name: 'Higher Secondary School Certificate (HSC)',
            year: '2014',
            section: 'Science',
            institute: 'Masjid Mission Academy (School & College)',
            result: '3.90',
        },
        {
            name: 'Secondary School Certificate (SSC)',
            year: '2012',
            section: 'Science',
            institute: 'Paranpur Kamil Madrasah',
            result: '4.94'
        },
    ],
    trainings: [
        {
            name: 'Web Development',
            year: '2016',
            institute: 'Hypertag Solution',
            duration: '4 month',
            program: 'PHP, Laravel',
        },
        {
            name: 'Web Design',
            year: '2016',
            institute: 'Creative It Institute',
            duration: '4 month',
            program: 'HTML, CSS, Bootstrap, Javascript',
        },
        {
            name: 'Web Design',
            year: '2015',
            institute: 'IIT-University of Dhaka',
            duration: '4 month',
            program: 'HTML, CSS, Bootstrap',
        },
    ],
    projects: [
        {
            project_name: 'E-Commarce (Web & Api)',
            client: 'Red Origin',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js,Firebase, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'ecommarce/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'http://www.redorigin.com.bd/',
        },
        {
            project_name: 'Vendor Management',
            client: 'Iddrak',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js,Firebase, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'findallvendor/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'https://findallvendors.com/',
        },
        {
            project_name: 'Training Management',
            client: 'Iddrak',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js,Firebase, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'training/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'https://findtrainingprograms.com/',
        },
        {
            project_name: 'Microfinance Solution',
            client: 'TMSS-ICT',
            role: 'Team Member',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.jpg',
            folder: 'mikrof/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'https://mikrof.com/',
        },
        {
            project_name: 'Water Supply Management',
            client: 'TMSS-ICT',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'shitol/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'http://shitolpani.com/',
        },
        {
            project_name: 'Online newspaper',
            client: 'Youthjournal',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'youthjournal/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'http://youthjournal.net/bn',
        },
        {
            project_name: 'Medical instrument Supply',
            client: 'Basuka',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.js, SQL',
            thumbnail: 'thumbnail.png',
            folder: 'bashuks/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: 'http://basukacorp.com/',
        },
        {
            project_name: 'PressPhoto (Api)',
            client: 'PressPhoto',
            role: 'Developer',
            technology: 'PHP, Laravel, Firebase',
            thumbnail: 'thumbnail.png',
            folder: 'pressphoto/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: '#',
        },
        {
            project_name: 'Etraining',
            client: 'Etraining',
            role: 'Developer',
            technology: 'PHP, Laravel, Vue.Js',
            thumbnail: 'thumbnail.png',
            folder: 'etraining/',
            images: ['thumbnail.png','01.png', '02.png', '03.png', '04.png'],
            details: '',
            url: '#',
        },
    ],
    imageBasePath: 'img/projects/',
};